### ISSUE TITLE
成功率很低

### ISSUE THREAD

**Issue by ljy559** [Fatpandac/hackcqooc#12]
成功率很低，10个基本上一半失败

**Comment by ljy559** [comment]
Traceback (most recent call last):
  File "D:\software\python3.9\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "E:\pythonproject\fuck_cqooc-master\src\skipper.py", line 27, in run
    self.skip(self.sectionList)
  File "E:\pythonproject\fuck_cqooc-master\src\skipper.py", line 32, in skip
    result = self.core.skip_section(i)
  File "E:\pythonproject\venv\lib\site-packages\hackcqooc\core.py", line 186, in skip_section
    status_code = skip_res.json()["code"]
  File "E:\pythonproject\venv\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Fatpandac** [comment]
限制升级，刷课间隔时间变长，后续会尝试修复，同时也欢迎您提交 PR 修复这个问题
> 刷课的间隔时间大于两分钟左右成功率会高很多

**Comment by Mrkk1** [comment]
也许可以尝试在失败之后 进入一段更长的等待，然后尝试重新请求该小结，直到此小结成功为止。这样用户就无需因为刷课失败重新选中科目后刷课了
