### ISSUE TITLE
只用以下账号，获取课程出错

### ISSUE THREAD

**Issue by Mrkk1** [Fatpandac/hackcqooc#17]
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\xa0' in position 80110: illegal multibyte sequence
Call stack:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 995, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1008.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Administrator\Desktop\xygxpt-main\skipView.py", line 47, in choose_course
    task_list = page.core.get_course_lessons(course_id).get("data")
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\hackcqooc\core.py", line 126, in get_course_lessons
    temp = self.__request.do_get(
  File "C:\Users\Administrator\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\hackcqooc\request.py", line 60, in do_get
    logging.info(f"{res.text}")
    
    
账号：17323676053
密码：Fyb094874
说明：客户端无法正常显示已经完成的科目，控制台报错

**Comment by Mrkk1** [comment]
其他账号测试正常 很怪，怪的很

**Comment by Fatpandac** [comment]
无法复现，没有效的测试账户。
如果可以提供请发到我的邮箱 i@fatpandac.com

**Comment by Mrkk1** [comment]
已发送到您的私人邮箱




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月29日(星期一) 中午1:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Fatpandac/hackcqooc] 只用以下账号，获取课程出错 (Issue #17)





 
无法复现，没有效的测试账户。
 如果可以提供请发到我的邮箱 ***@***.***
