### ISSUE TITLE
平台接口改动

### ISSUE THREAD

**Issue by Mrkk1** [Fatpandac/hackcqooc#45]
平台改动了接口，无法获取到课程信息。表现为：获取到xsid后可以现实课程列表，当点击课程列表后，无法获取课程的详细信息，报错为：
(base) xxxx@xxxxx xygxpt % /Users/xxxx/micromamba/bin/python /Users/xxxx/Documents/xy
gxpt/app.py
{'status': 'ok', 'code': 0, 'xsid': '7DD88B736CA937E4'}
Exception in thread Thread-48:
Traceback (most recent call last):
  File "/Users/xxxx/micromamba/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/xxxx/micromamba/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/xxxxxx/micromamba/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/xxxx/micromamba/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxxx/micromamba/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/xxxx/micromamba/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/xxxxx/Documents/xygxpt/skipView.py", line 50, in choose_course
    task_list = page.core.get_course_lessons(course_id).get("data")
  File "/Users/xxxxxx/micromamba/lib/python3.9/site-packages/hackcqooc/core.py", line 225, in get_course_lessons
    temp = self.__request.do_get(
  File "/Users/xxxxx/micromamba/lib/python3.9/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
请忽略路径中的xxxxx，那是我的root昵称

**Comment by RX-105** [comment]
关于你提到的问题，我测试了一下，cqooc的api返回内容是502 Bad Gateway，也就是问题来自cqooc，而非hackcqooc。如下图所示，现在这个api已经恢复正常了。感谢你的关注。
![image](https://github.com/Fatpandac/hackcqooc/assets/94608280/a2b2d179-7663-421b-b5e6-df9b98cfd96f)
